### ISSUE TITLE
BlitFill issue on high resolution images

### ISSUE THREAD

**Issue by MichaelQuint** [fschultz/NetImageLibrary#8]
I'm getting strange issues with the BlitFill method on high resolution images, im using the method to watermark the images on my website with a watermark image ive created. I followed the tutorial to do so, for smaller images it works fine, for others not so much. Ive attached the results below:

image "7.jpg" ( the last one ) is correct.

![11](https://cloud.githubusercontent.com/assets/926496/11908907/bedfc434-a5ae-11e5-96a1-a68f4fa950db.jpg)
![12](https://cloud.githubusercontent.com/assets/926496/11908909/c277158e-a5ae-11e5-8a34-8141070d7fa5.jpg)
![4](https://cloud.githubusercontent.com/assets/926496/11908918/e0474930-a5ae-11e5-9b80-7aae8404c6b5.jpg)
![7](https://cloud.githubusercontent.com/assets/926496/11908910/cd71ff76-a5ae-11e5-9e0f-7e5e896b5f5f.jpg)

**Comment by MichaelQuint** [comment]
Also, here is the code im using to product the results.

                    KalikoImage img = null;
                    using (var ms = new MemoryStream(picture.Image))
                    {
                        img = new KalikoImage(ms);
                        img.BlitFill(watermark);
                    }

                    byte[] image = null;
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        img.SaveJpg(memoryStream, 99);
                        image = memoryStream.ToArray();
                    }

**Comment by fschultz** [comment]
Thank you for the bug report! I will look into why this happens.

**Comment by fschultz** [comment]
The issue seems to be related to the DPI resolution of the images. An image with for instance 300 DPI results in the same error as seen in the attached images, while the exact same image but in 96 DPI produces the correct result. I hope to have a fix for this soon.

**Comment by MichaelQuint** [comment]
Awesome, I appreciate the support!

**Comment by fschultz** [comment]
I've created a new branch where all constructors should be DPI-independent. It would be great if you can verify if this solves your problem, thanks! 

The new branch is: https://github.com/fschultz/NetImageLibrary/tree/dpi-fix

**Comment by MichaelQuint** [comment]
Yessir, that did the trick. So converting the Image to Bitmap fixes this? very intereting

**Comment by fschultz** [comment]
Great! Yes, it seems that wrapping it as Bitmap is the easiest way to keep everything intact and in the same time resetting the DPI-information.
